// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class DZ_28 {
    private WebDriver driver;

    String url = "https://www.saucedemo.com/";
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void dZ281() {
        driver.get(url);
        driver.manage().window().setSize(new Dimension(945, 1020));
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-backpack")).click();
        driver.findElement(By.cssSelector(".shopping_cart_badge")).click();
        driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Tata");
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Sha");
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("00000");
        driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
        assertThat(driver.findElement(By.cssSelector(".complete-text")).getText(), is("Your order has been dispatched, and will arrive just as fast as the pony can get there!"));
    }
        @Test
        public void dZ282() {
            driver.get(url);
            driver.manage().window().setSize(new Dimension(945, 1020));
            driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
            driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
            driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
            driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
            driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);
            driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
            driver.findElement(By.id("react-burger-menu-btn")).click();
            driver.findElement(By.id("logout_sidebar_link")).click();
            driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
            assertEquals(url, driver.getCurrentUrl());
            assertNotNull(driver.findElement(By.id ("login-button")));
        }
}



